# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v0.0.0', max_length=6)),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Mes',
            },
        ),
    ]
